### ISSUE TITLE
Broken links in README `Function reference` section

### ISSUE THREAD

**Issue by Faizal-Eeman** [uclahs-cds/package-BoutrosLab-plotting-general#153]
The functions link in the table are broken.
https://github.com/uclahs-cds/package-BoutrosLab-plotting-general/tree/main#function-reference

We can either,

1. [Set up a redirect](https://dev.to/steveblue/setup-a-redirect-on-github-pages-1ok7) on GitHub pages
or
2. Update the existing links

**Comment by tyamaguchi-ucla** [comment]
@dan-knight looks like we need to fix links here as well. https://uclahs-cds.github.io/package-BoutrosLab-plotting-general/
