### ISSUE TITLE
Adding non-vertical line segments to scatter plots

### ISSUE THREAD

**Issue by Nick-Nunley** [uclahs-cds/package-BoutrosLab-plotting-general#169]
Hello. If I am reading this block of code correctly,
```
# if requested, add additional lines
			if (add.line.segments) {

				for (i in 1:length(line.start)) {
					with(
						data = new.env(),
						expr = panel.segments(
							x, line.start[[i]][subscripts], x, line.end[[i]][subscripts],
							col = line.col[[i]],
							lwd = line.lwd[[i]],
							lineend = 1
							)
						);
					}
				}
```
it seems that the `create.scatterplot()` function in BPG doesn't support non-vertical line segments. Is this supposed to be the case? Would we want to consider adding the capability of handling separate x and y component inputs for `line.start` and `line.end` to add various sloped line segments?

https://github.com/uclahs-cds/package-BoutrosLab-plotting-general/blob/448df842de311386059b6285fa5e843c14306778/R/create.scatterplot.R#L1211C4-L1225C6

**Comment by maotian06** [comment]
@Nick-Nunley 
I think it doesn't support non-vertical lines, but you could save the `create.barplot()` object and add another [layer](https://latticeextra.r-forge.r-project.org/man/layer.html) or [a panel line](https://stackoverflow.com/questions/32868230/adding-additional-panel-plots-to-an-xy-lattice-plot) in the original function to achieve it. Paul has posted a suggestion in a similar issue #131 that can be a good reference for your issue as well!

**Comment by Nick-Nunley** [comment]
> I think it doesn't support non-vertical lines, but you could save the create.barplot() object and add another [layer](https://latticeextra.r-forge.r-project.org/man/layer.html) or [a panel line](https://stackoverflow.com/questions/32868230/adding-additional-panel-plots-to-an-xy-lattice-plot) in the original function to achieve it. Paul has posted a suggestion in a similar issue https://github.com/uclahs-cds/package-BoutrosLab-plotting-general/issues/131 that can be a good reference for your issue as well!

I see. Thanks @maotian06. I will go ahead and close this issue.

**Comment by Nick-Nunley** [comment]
Duplicate of #131
